### ISSUE TITLE
Leverage GitHub cache to improve setup-matlab time 

### ISSUE THREAD

**Issue by acampbel** [libprima/prima#19]
This repository is very active building MATLAB projects many times a day. Also, it is leveraging the v2-beta of the setup-matlab action. You may be interesting in caching the MATLAB installations for improved performance. Note this may use a significant portion of your cache space, but nonetheless may be worth it for this project. To see an example of a project leveraging GitHub actions cache for MATLAB look [here](https://github.com/acampbel/ci-configuration-examples-expo/blob/main/.github/workflows/ci.yml).

**Comment by zaikunzhang** [comment]
Hi @acampbel ,

The availability of MATLAB on GitHub Actions is life-changing for me. Without this, the CI of the [PRIMA](http://www.libprima.net) project would not be possible. Thank you and your colleagues very much!

Thank you very much for your suggestion. Caching is a great idea! I tried caching the installation of MATLAB some time ago, but did not succeed. 

After reading your message and [your example](https://github.com/acampbel/ci-configuration-examples-expo/blob/main/.github/workflows/ci.yml), I tried it again. It works. Thank you very much!

Best regards,
Zaikun
