### ISSUE TITLE
SMALL_TR_RADIUS has same value as INFO_DFT

### ISSUE THREAD

**Issue by jschueller** [libprima/prima#26]
see https://github.com/libprima/prima/blob/main/fortran/common/infos.f90:
```
integer(IK), parameter :: INFO_DFT = 0
integer(IK), parameter :: SMALL_TR_RADIUS = 0
```
so the return value is ambiguous: we dont know why the algo returns 0

**Comment by jschueller** [comment]
@zaikunzhang any clue ?

**Comment by zaikunzhang** [comment]
> @zaikunzhang any clue ?

Hello @jschueller . Thank you for pointing this out. This is intended, because SMALL_TR_RADIUS is the default exiting status of all the five algorithms. Thank you.

**Comment by jschueller** [comment]
ok, thanks
