### ISSUE TITLE
`cmake_nagfor` fails but is marked as a success

### ISSUE THREAD

**Issue by zaikunzhang** [libprima/prima#57]
Sorry to bother you again, Julien @jschueller . 

[cmake_nagror](https://github.com/libprima/prima/blob/main/.github/workflows/cmake_nagfor.yml) fails (for the moment), but is always marked as a success. See 
https://github.com/libprima/prima/actions/workflows/cmake_nagfor.yml
https://github.com/libprima/prima/actions/runs/6157074599. 
Is this intended? Thanks.

**Comment by jschueller** [comment]
maybe because of the "continue-on-error: true" ?

**Comment by zaikunzhang** [comment]
fixed  by 72edcdeef4fdb45b385084172464a1490b5550d1
