### ISSUE TITLE
fork scheduled workfows

### ISSUE THREAD

**Issue by jschueller** [libprima/prima#93]
each fork of prima runs scheduled workflows on its own, thats unnecessary and may slow users own workflows

this is a known issue
https://github.com/orgs/community/discussions/16109

the solution would be adding a condition for each job:
```if: github.repository == 'libprima/prima'```

**Comment by zaikunzhang** [comment]
Hi @jschueller ,

I agree that it is an issue. It would be desirable if there was a systematic way to specify the repo where a **workflow** should run. However, doing it on the job level seems not ideal. 

The solution I suggest for the moment is to [disable the workflow manually](https://docs.github.com/en/actions/using-workflows/disabling-and-enabling-a-workflow). 

Also, I would like to remark that all workflows with a cron schedule are disabled by default on forks.

**Comment by jschueller** [comment]
sorry, but that's not what I experienced on my fork: scheduled workflows ran there too  slowing down my own jobs from my other repos

**Comment by zaikunzhang** [comment]
> sorry, but that's not what I experienced on my fork: scheduled workflows ran there too slowing down my own jobs from my other repos

There is probably a bug on the GitHub side. I also experienced that some scheduled workflows are enabled unintendedly, but I cannot reproduce the problem. If you can, you may report to GitHub. 

For the moment, the solution is to disable the workflows manually. 

Thank you.

**Comment by jschueller** [comment]
the issue has been reported:
https://github.com/orgs/community/discussions/16109
the solution is to explicitely disable it via a job condition:
https://github.com/libprima/prima/pull/94

**Comment by zaikunzhang** [comment]
I guess it was reported befor GitHub implements "disable scheduled workflows on forks by default".

The (new) problem is, the implementation seems not always work.

Thanks.

**Comment by jschueller** [comment]
seems its disabled now on new forks

**Comment by zaikunzhang** [comment]
Great. Thanks. 

I still observe from time to time that they are enabled on some forks. But I have not recognized the pattern yet. So do not be surprised if they come back ...
