### ISSUE TITLE
Enable the C interface to accept `nlconstr0` and `f0`

### ISSUE THREAD

**Issue by zaikunzhang** [libprima/prima#99]
See the discussion at 

https://github.com/libprima/PRIMA.jl/issues/14#issuecomment-1770266055

for the reason.

Since C does not support optional inputs (unfortunately), let us do the following: 

1. if the user does not want to input `nlconstr0`, then it should be set to `NULL`;
2. if the user does not want to input `f0`, then it should be set to `NaN`;
3. in `cobyla_c.f90`, check the values of `nlconstr0` and `f0` to decide whether to call `cobyla` with `nlconstr0` &`f0` or without them (they are optional inputs to `cobyla`);
4. (an alternative to 3) in `cobyla_c.f90`, check the values of `nlconstr0` and `f0`. If `nlconstr0` is `NULL` of `f0` is `NaN`, then call `calcfc` to evaluate them; afterwards, call `cobyla` with `nlconstr0` and `f0`. 

Thanks.

**Comment by jschueller** [comment]
optional options could be passed via a pointer to a struct:
```
prima_options opt;
prima_init_options(&opt);
opt.nlconstr0 = ...
opt.f0 = ...
opt.eta1 = ...
prima_cobyla(..., &opt) // with options
prima_cobyla(..., NULL) // without options
```
